### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by yusiwen** [ooxi/xml.c#18]
In `xml.c` , function `xml_easy_child()`

lien 835-837:

```c
} else {
  return 0;
}
```

It should be:
```c
} else {
  va_end(arguments);
  return 0;
}
```

And line 843 - 845:

```c
if (!next) {
  return 0;
}
```

It should be:
```c
if (!next) {
  va_end(arguments);
  return 0;
}
```

**Comment by ooxi** [comment]
Yes, you are right, good catch! Do you want to prepare a pull request with the fix?

**Comment by yusiwen** [comment]
OK, I've just released a pull-request, plz check it.

**Comment by ooxi** [comment]
Great work, thank you!
