### ISSUE TITLE
Parsing error with xml header and empty element

### ISSUE THREAD

**Issue by Ludovic37-center** [ooxi/xml.c#26]
Hi,

I'm a french embedded developper (sorry for my english mistakes)
I receive data from a distant system, but i can parse it.
There is two errors:
XML header:
`<?xml version="1.0" encoding="utf-8" standalone="no" ?>`

Empty element:
`<vehicleJourney/>`  there is no space before />

How can i solve these two errors ?
Thanks
Best regards !

**Comment by ooxi** [comment]
Unfortunately, `xml.c` currently supports neither, xml header nor short closed tags. While these issues can be solved, I strongly recommend against using `xml.c` for parsing untrusted data.

I would recommend looking at [libxml2](http://xmlsoft.org/) or maybe [TinyXML-2](http://www.grinninglizard.com/tinyxml2/) if you are able to use C++.

Really `xml.c` should not be used for anything but known good tiny files, like a config file for an embedded application. Sorry to not have a more positive answer for you.

Feel free to reopen this ticket if you need any support :-)
