### ISSUE TITLE
Couldn't clone repository on Windows

### ISSUE THREAD

**Issue by TheoryOfNekomata** [ooxi/xml.c#35]
The `.mc/ubuntu:22.04.yaml` file is an invalid Windows path since colons are reserved for drive letters.

**Comment by devintrowbridge** [comment]
I don't see any immediate reason we couldn't replace that with some other character.

**Comment by ooxi** [comment]
Thank you very much for the report! Unfortunately I did not check this on Windows but it should be fixed now thank's to @devintrowbridge's PR!
