### ISSUE TITLE
Failure to parse xml attributes in tags

### ISSUE THREAD

**Issue by roticv** [ooxi/xml.c#9]
It looks like ooxi/xml.c is unable to parse attributes in tags. It fails with "xml_parser_error at 50:25: xml_parse_node::tag missmatch" and it is because it assumes that the value of tag_open = tag_close without stripping out the attributes before comparing.

**Comment by ooxi** [comment]
You are correct, parsing XML with attributes is not supported by xml.c

Implementing attribute parsing shouldn't be that complicated but is currently not in the scope of this XML subset parser (nevertheless, patches are welcome!). The API could be extended by `xml_node_attribute` very cleanly.

That being said, I'm leaving this ticket open as an reminder to specify the XML subset supported by xml.c :)

**Comment by DevNaga** [comment]
it cannot parse comments as well.. if i have comments in the document, it crashes with a coredump..

**Comment by ooxi** [comment]
@DevNaga thank you very much for your interest in this project! Currently parsing comments is not supported, but you are correct it should be (they should be stripped).

I will open a separate issue for that

**Comment by ooxi** [comment]
Thanks to the work of @Molorius and @Isty001, xml.c can now also parse arguments. Feel free to reopen this issue if you have any more questsions :-)
